import React from 'react'
import TermsImg from '../assets/images/terms-inner-page.png'
function TermsConditions() {



  React.useEffect(() => {
    window.scrollTo(0, 0);
}, []);
  return (
    <>
      <div className='sec_mt-100'>
        <div className="c_container">
          <div className="row m-0 flex-column-reverse flex-lg-row">

            <div className="col-lg-6">
              <h1 className='t_one fw-900'>
                TERMS / CONDITIONS
              </h1>
              <p className='p_two mt-2 mt-md-4'>
                When used herein, the term “ReverseAds” (Thailand) Co. Ltd. dba ReverseAds and the term “Quotations” means the total price quoted to a customer (“Customer”) by ReverseAds to utilize action-producing advertisements, or surveys, through the use of coupons, vouchers, tickets, promotions and campaigns, supplied by ReverseAds (“ReverseAds Ads”), to generate leads and awareness and to build loyalty programs and relationship management to support the Customer’s inbound and outbound services (“ReverseAds Services”). <br /> <br />
                ReverseAds Services are subject to the following Advertising Terms and Conditions as the same may from time to time be amended, modified or supplemented by ReverseAds:<br /> <br />
                1. All quotations offered through the self-service portal are offered for immediate acceptance and are firm for one (1) business day. ReverseAds reserves the right to revise any quotation offered through the self-service portal after one (1) business day. All quotations offered by a sales representative of ReverseAds are offered for immediate acceptance and are firm for three (3) business days. ReverseAds reserves the right to revise a quotation offered by a sales representative of ReverseAds after three (3) business days. Quotations are based on specifications submitted by the Customer. If the Customer requests any changes to those specifications, the Quotation may be revised and the Customer will be deemed to have accepted such price revisions unless the Customer notifies ReverseAds within five (5) days of receiving such revised Quotation.<br /> <br />
                2. All sums and/or calculations referenced in the Quotation are in USD. In the event that any sum needs to be converted into another currency, ReverseAds shall use the exchange rate published by a reputable third party (such as XE.com).<br /> <br />
                3. One hundred percent (100%) of a Quotation must be paid to ReverseAds by the Customer within five (5) days of any cancellation of the Quotation by the Customer and/or its agent signing on behalf of the Customer.<br /> <br />
                4. Materials provided by the Customer for inclusion in any ReverseAds Ads shall be delivered to ReverseAds on or before the due date specified in the quotation, failing which they will not be included in such ReverseAds Ads.<br /> <br />
                5. ReverseAds Ads must be approved in writing by ReverseAds and ReverseAds reserves the right to alter or refuse any, or part thereof, ReverseAds Ad.<br /> <br />
                6. Proofs submitted to the Customer should be reviewed and returned electronically to ReverseAds marked “O.K.” or “O.K. with corrections” and electronically signed with the initials of a person duly authorized to approve such proofs. If a revised proof is desired, such a request must be made when the proof is returned. Retouching of ReverseAds Ads is not included in quotations and is charged on an actual time basis. ReverseAds is not responsible for errors in any proof supplied and/or approved by the Customer.​<br /> <br />
                7. ReverseAds reserves the right to review the Customer’s ad content to ensure that the ReverseAds Ads are approved by both ReverseAds and by its partner networks. Such creative requirements and policies are important for any campaign. The ad content guidelines outlined below apply to the Customer’s ad and website images.<br /> <br />
                i. Adult Content: ReverseAds may approve ReverseAds Ads that depict nudity, graphic language, or adult concepts, subject to the terms and conditions of its partner networks and advertising exchanges.<br /> <br />
                ii. Alcohol: ReverseAds may approve ReverseAds Ads that depict alcohol or alcohol consumption, subject to the terms and conditions of its partner networks and advertising exchanges.<br /> <br />
                iii. Cannabis: ReverseAds may approve ReverseAds Ads that depict cannabis or cannabis use or consumption, subject to the terms and conditions of its partner networks and advertising exchanges.<br /> <br />
                iv. Body images: In line with ReverseAds’ policy on Adult Content, sexualized images will not be approved. Avoid nudity (implied or explicit), unnecessary skin exposure or cleavage, or other tactics designed to solicit a sexual response. ReverseAds Ads will be subject to the terms and conditions of its partner networks and advertising exchanges. For example, Facebook doesn’t permit the use of ad images that imply ideal or undesirable body image, including “before and after” photos, images that imply unlikely results, or images that draw unnecessary attention to body parts.<br /> <br />
                v. Brand Notification: The Customer’s visitor should be able to have a clear understanding of where they'll be going when they click the ReverseAds Ad. ReverseAds requires that the brand shown in any ReverseAds Ads matches the brand of the destination landing page.<br /> <br />
                vi. Shock Value: ReverseAds will not approve any ReverseAds Ads that use images that are visually disturbing, gory, or designed to shock or scare.<br /> <br />
                vii. Spam Tactics: Tactics to mislead a visitor are strictly prohibited. ReverseAds will not approve ReverseAds Ads that: Imitate computer functions such as system messages, progress bars, or virus warnings; Mimic the function of other types of media, such as appearing to be an embedded video; or initiate prompts to download files or software after the click.<br /> <br />
                viii. Strobing and Flashing: Strobing, flashing backgrounds, or otherwise distracting ReverseAds Ads are not permitted. Do not attempt to overtly distract the user from page content.<br /> <br />
                ix. Toubon Law (France): France’s 1994 Toubon Law requires that ads in France must be only in French, or include a French translation. This applies to ads shown on any French IP address (not just on or from domains). To serve ReverseAds Ads in France, please make sure that the ad content is in French language.<br /> <br />
                x. Personally Targeted Messaging: Due to the highly targeted nature of retargeting, ReverseAds is especially sensitive to user privacy. This is something to be particularly careful with if your website focuses on products or services for a specific audience. Even if your website meets ReverseAds content requirements, targeted messaging that implies knowledge of an individual’s personal circumstances will not be approved by ReverseAds.
                <br /> <br />
                xi. Violence and Weapons: ReverseAds will not approve ReverseAds Ads that depict violence, including pictures of guns or other firearms.<br /> <br />
                8. It is understood and agreed that, unless otherwise specified, any customer lists and any other data furnished to the Customer by ReverseAds (“Confidential Information”) are furnished for one time use only and shall remain the proprietary and confidential property of ReverseAds. Any systems or programs developed or supplied by ReverseAds in the provision of ReverseAds Services shall also remain the property of ReverseAds and be considered Confidential Information. Aside from the permitted uses under this Agreement, the Customer agrees to protect any Confidential Information, keep it confidential, and not disclose or use such Confidential Information except for the purposes contemplated hereby or to disclose to third parties the terms set forth in this Agreement.<br /> <br />
                9. Sketches, dummies or copies submitted by ReverseAds remain its property and no use of the same shall be made or any idea obtained there from shall be used without the prior written consent of ReverseAds.
                <br /> <br /> 10. THE WARRANTIES IN THIS AGREEMENT ARE EXCLUSIVE AND MADE EXPRESSLY IN LIEU OF ALL OTHER WARRANTIES, REPRESENTATIONS AND REMEDIES: (1) WRITTEN OR ORAL; (2) EXPRESS OR IMPLIED; (3) AT LAW, IN EQUITY OR UNDER CONTRACT, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTY OF MERCHANTABILITY, NON-INFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, OR OTHERWISE; AND (4) NOTWITHSTANDING ANY COURSE OF DEALING BETWEEN THE PARTIES OR CUSTOM AND USAGE IN THE TRADE TO THE CONTRARY.
                <br /> <br /> 11. The nature of the business of ReverseAds is such that it cannot guarantee or be financially responsible for the consequences of any delay or failure to provide any ReverseAds Services by a stipulated date. In addition, the liability of ReverseAds for any other type of loss, damage, or injury of any kind whatsoever incurred or suffered by the Customer or by any other person shall not exceed the direct fees paid by Customer to ReverseAds for direct services rendered (specifically, excluding any amounts of money paid to ReverseAds for services to be rendered by other third parties) for such ReverseAds Services. In no event (including but not limited to fundamental breach of contract, breach of a fundamental term of the contract and the negligence or gross negligence of ReverseAds, its employees or agents, and whether arising from miss delivery, failure to deliver or delay in delivery) shall ReverseAds be liable, whether through the suit of Customer or any third party, and whether in contract, tort or otherwise, for any indirect, incidental, consequential, punitive or special damages or for damages for loss of earning of profit
                <br /> <br />12. All Quotations for ReverseAds Services are exclusive of any and all applicable taxes, including federal tax, value added tax or any other sales tax, which shall be added to the Quotation or otherwise included in any relevant calculation, and are to be borne by the Customer, and where any withholding tax or similar deduction is required to be made, the amount of the Invoice shall be paid net of that deduction.<br /> <br /> 13. ReverseAds, or its sales representatives or designates, as the case may be, will invoice the Customer for the Quotation (the “Invoice”) in advance of each applicable month in which ReverseAds Services are to be rendered (the “Campaign”). Payment to ReverseAds of any Invoice must be made at least seven (7) business days prior to the effective date of the Customer’s Campaign (the “Campaign Launch”). In the event that payment of an Invoice is not made in advance of seven (7) business days prior to the respective Campaign Launch, ReverseAds reserves the right, but not the obligation, to delay, until the time that such payment is made, or otherwise terminate the Campaign Launch. In addition, the Customer also agrees to pay all costs of collection ReverseAds incurs, including legal fees and expenses, should a default in payment to ReverseAds occurs.
                <br /> <br /> 14. If the creditworthiness of the Customer at any time becomes unsatisfactory to ReverseAds, ReverseAds reserves the right to require payment for any ReverseAds Services in advance, or provision of satisfactory security for payment.
                <br /> <br /> 15. Subject to the credit approval, ReverseAds may require prepayment for any ReverseAds Services rendered to a new Customer.
                <br /> <br /> 16. ReverseAds shall not be liable for any failure to provide ReverseAds Services as a result of strike, fire, accident, civil disturbance, terrorist acts, unusual market conditions, media delay or interruption, or any other cause beyond the control of ReverseAds.<br /> <br /> 17. Customer shall indemnify and save harmless ReverseAds, its employees, agents and affiliates, from and against all claims, losses, costs and damages (including indirect, special and consequential damages and/or for damages for loss of earning of profits and including legal fees of a solicitor and his/her own Customer basis and interest) incurred or suffered by ReverseAds, its employees, agents and affiliates, in connection with or arising out of:<br /> <br />
                i. any infringement of alleged infringement by the Customer of any copyright, trademark, trade name or other proprietary right;<br /> <br />
                ii. any claim that the distribution of materials provided by the Customer constitutes an unlawful violation and/or violation of the Competition Act or any other law (including, without limitation, misleading advertising or promotion of a product by means of an unlawful or allegedly unlawful contest, lottery or game of chance or skill); and <br /> <br />
                iii. any other claims made against the Customer or ReverseAds in respect of the Customer’s advertisement.​Upon ReverseAds’ request, the Customer agrees, at its own cost and expense, to defend any such actions, claims or demands on behalf of ReverseAds using legal counsel reasonably acceptable to ReverseAds.
                <br /> <br /> 18. These terms and conditions represent the entire agreement of the parties and no terms, representations or conditions in any way modifying or changing the provisions stated herein shall be binding upon ReverseAds unless made in writing and signed and approved by an authorized representative of ReverseAds.
                <br /> <br />
                19. This Agreement is the complete and exclusive statement of the mutual promises and consideration of the parties, and supersedes and cancels any previous written and oral agreements and communications relating to the subject matter of this Agreement and/or any proposed terms and conditions stipulated in the Customer’s purchase order, request for quotation, or similar form.<br /> <br />
                20. This Agreement shall be governed by the laws of the Province of Ontario and the laws of Canada applicable therein. Each party hereto irrevocably waives any objection on the grounds of venue, forum non-convenience or any similar grounds and irrevocably consents to service of process by mail or in any other manner permitted by applicable law and consents to the jurisdiction of the courts of the Province of Ontario.<br /> <br />
                21. The Customer may not, without ReverseAds’ prior written consent, assign, pledge, grant a security interest in or otherwise transfer this Agreement or any of its right, or obligations under this Agreement, to any person.<br /> <br />
                22. Except as expressly provided in this Agreement, no amendment or waiver of this Agreement shall be binding unless executed in writing by the party to be bound thereby.<br /> <br />
                23. If any provision of this Agreement shall for any reason be held illegal or unenforceable, such provision shall be deemed separable from the remaining provisions of this Agreement and shall in no way affect or impair the validity or enforceability of the remaining provisions of this Agreement.<br /> <br />
                24. ReverseAds may terminate this Agreement by notice in writing to the Customer if any of the following occur: (a) the Customer breaches any terms of this Agreement; (b) the Customer makes any attempt to assign or otherwise transfer any of its rights under this Agreement; or (c) the Customer is dissolved, becomes insolvent or is unable to pay its debts or fails or admits in writing its inability generally to pay its debts as they become due, make a general assignment for the benefit of its creditors, institutes or has instituted against it a proceeding seeking a judgment of insolvency or bankruptcy or has a secured party take possession of all or substantially all of its assets or has a distress, execution or other legal process levied, enforced or sued on or against all substantially all of its assets.<br /> <br />
                25. Upon termination of this Agreement, the Customer’s obligations under sections 2, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20 and 21 shall survive the termination and the Customer’s rights this Agreement shall immediately cease. Subject to section 13, above, termination of this Agreement shall not limit either party from pursuing any other remedies available to it, including injunctive relief, nor shall such termination relieve the Customer from its obligations to pay fees accrued prior to the termination. Click Fraud Statement At ReverseAds, it is our promise to always do right by our clients. We take all possible measures to ensure that we prevent as much invalid or fraudulent traffic as possible, with over 99% of invalid traffic being filtered out by our proactive measures. We have systems in place to filter and scrub IP data that is deemed to be invalid, our methods are proactively blocking invalid clicks and preventing the traffic from reaching our clients websites. Our automated detection algorithm looks for patterns will filtering through IPs, click redundancies and timestamp comparisons in order to block click fraud. We have a dedicated team of Safety and Trust experts analyzing new threats and constantly improving our systems filtering capabilities. We take all reports of invalid clicks very seriously and take time to investigate each case to determine click validity. Should fraudulent active be found to have occurred we will credit the advertiser the clicks back. Refund Policy All services that ReverseAds offers are considered to be provided on a strictly prepaid basis. Refund Policy: All services rendered by the ReverseAds are provided on a non-refundable basis.
              </p>


              <div className='p-4'></div>

            </div>

            <div className="col-lg-6 position-relative text-center text-md-end">
              <img src={TermsImg} className="sticky_img " alt="" />
            </div>

          </div>
        </div>
      </div>
    </>
  )
}

export default TermsConditions